// Blueprint related constants

export const menuItems = ["Jobs", "Discrepancies", "RFIs", "Blueprints"] as const;

export const jobCategories = [
  "Electrical",
  "Concrete",
  "Roofing",
  "Steel",
  "Plumbing",
  "Framing",
  "Flooring",
  "Glazing",
  "HVAC",
  "Drywall",
  "Masonry",
  "Doors and Windows",
] as const;

export const progressSteps = [
  { label: "Uploading blueprint...", duration: 1000 },
  { label: "Processing document...", duration: 2000 },
  { label: "Analyzing construction elements...", duration: 3000 },
  { label: "Detecting discrepancies...", duration: 2000 },
  { label: "Generating RFIs...", duration: 2000 },
  { label: "Finalizing analysis...", duration: 1000 },
] as const;

// Prompts personalizados por categoría (nivel de detalle máximo)
export const categoryPrompts: Record<string, string> = {
  Electrical:
    "Perform a comprehensive electrical takeoff based on the full electrical drawing set, including power plans, lighting plans, panel schedules, and riser diagrams. Identify and quantify all electrical components such as main service equipment, distribution panels, circuit breakers, transformers, receptacles, switches, lighting fixtures, emergency and exit lighting, fire alarm devices, low voltage systems, and conduit/tray runs. Extract conduit and wire lengths based on scaled measurements and routing diagrams. Cross-reference all symbols with the electrical legend, and verify locations of panels and equipment against architectural and structural constraints. Ensure all components comply with NEC (National Electrical Code) and local codes, especially for load balancing, breaker sizing, grounding, and arc fault protection. Detect conflicts with plumbing, HVAC, or fire protection routing, especially in ceiling or wall cavities. Confirm GFCI and AFCI placements per code, and validate that all electrical loads are reflected in the panel schedules and match connected devices in the field.",

  Concrete:
    "Conduct a detailed concrete takeoff using architectural, structural, and civil plans. Identify and quantify all cast-in-place and precast concrete components including spread footings, strip footings, grade beams, pile caps, piers, basement and slab-on-grade floors, shear walls, columns, beams, elevated decks, stairs, and ramps. Extract all dimensions from plans, sections, and details to calculate concrete volumes in cubic yards or cubic meters. Include formwork surface area for each element to support labor and material estimates. Identify all reinforcement specifications: bar sizes, spacing, bar marks from rebar schedules, hooks, splices, development lengths, and dowels. Include vapor barriers, expansion joints, construction joints, curing methods, and admixtures (if specified). Reference notes for concrete strength (PSI), mix design, slump, exposure class, and finish type (trowel, broom, etc.). Confirm embeds and sleeves shown in coordination with MEP plans. Validate phasing for multi-pour elements, and determine pump or crane access if necessary.",

  Roofing:
    "Execute a full roofing system takeoff by analyzing architectural roof plans, building sections, details, and structural framing. Identify all roofing assemblies including structure (joists, decking), insulation layers, vapor barriers, underlayment, primary roofing membrane (TPO, EPDM, asphalt, etc.), ballast/gravel if used, and surfacing. Quantify all materials based on actual roof slope using the rise/run factor to adjust plan area to true surface area. Include all parapets, coping caps, edge metals, expansion joints, roof drains, overflow scuppers, downspouts, and waterproofing details. Identify penetrations for mechanical curbs, skylights, roof hatches, vents, and plumbing stacks. Verify flashing conditions at walls, curbs, and edges. Account for pitch pockets, safety anchor points, and walk pads if specified. Check slope direction for proper drainage and verify if tapered insulation is used. Ensure all roof systems comply with local energy codes and warranty requirements from manufacturers.",

  Steel:
    "Perform an advanced structural steel takeoff using framing plans, structural details, schedules, and general notes. Identify all steel elements including wide flange beams, columns, HSS (hollow structural section) members, angles, channels, trusses, and joists. Record member designations, lengths, and placement using framing plans and section cuts. Include all base plates, bearing plates, stiffeners, bracing systems, and structural connections. Review connection details for weld types, bolt sizes, edge distances, and connection angles. Quantify shear plates, clip angles, gussets, moment connections, and welded assemblies. Cross-check structural notes for steel grade (e.g., A36, A992), shop vs field welds, fireproofing requirements, galvanization, and surface preparation. Flag coordination issues with architectural features, MEP systems, and ceiling conflicts. Ensure proper load transfer paths and member continuity across floors and expansion joints. Identify erection sequence if indicated, and include temporary bracing or supports if called for in the documents.",

  Plumbing:
    "Complete a highly detailed plumbing takeoff using plumbing plans, riser diagrams, fixture schedules, and specifications. Identify all systems: domestic cold water, hot water, hot water return, sanitary drainage, storm drainage, and vent piping. Include specialized systems such as grease waste, medical gas, or reclaimed water if applicable. Quantify all plumbing fixtures by location, type, and quantity per room (toilets, sinks, urinals, showers, floor drains, etc.). Extract pipe lengths, diameters, materials (PVC, copper, PEX, cast iron, etc.), insulation, and slope from scaled drawings and risers. Calculate pipe fittings (elbows, tees, couplings, reducers) based on routing complexity. Include valves, cleanouts, access panels, backflow preventers, water meters, PRVs, expansion tanks, and pumps. Verify code compliance for minimum pipe sizes, fixture unit calculations, venting, trap arms, and slope. Coordinate pipe penetrations through slabs, beams, and walls with structural drawings. Validate accessibility requirements and barrier-free fixture locations per ADA guidelines.",

  Framing:
    "Develop a comprehensive framing takeoff by examining architectural plans, structural drawings, wall types, and building sections. Identify and quantify all framing components for walls, floors, and roofs: including dimensional lumber, engineered wood products (LVL, PSL, Glulam), metal studs, blocking, headers, and fire blocking. Determine stud and joist spacing from framing plans or wall type schedules (typically 12”, 16”, or 24” o.c.). Calculate linear footage of each member size and total count based on layout. Include sill plates, top plates (single/double), trimmers, king studs, and cripple studs around openings. Quantify roof framing materials including rafters, purlins, trusses (with layout if provided), fascia boards, and ridge beams. Review structural framing details to determine connections (nails, screws, hangers, plates), sheathing thickness/type (OSB, plywood), and lateral bracing. Verify wall heights from sections and elevations. Adjust for platform vs balloon framing configurations, and validate load transfer at bearing points. Coordinate opening rough-ins with doors, windows, and mechanical penetrations.",

  Flooring:
    "Conduct a full flooring takeoff by using finish plans, room finish schedules, architectural plans, and details. Identify floor finishes by type and room (e.g., VCT, carpet, ceramic tile, hardwood, LVT, epoxy). Calculate square footage for each flooring material by measuring the area of each room or zone. Subtract permanent fixtures or casework areas if flooring is not installed beneath. Include base trim (cove base, rubber base) in linear feet along perimeters. Include underlayments, adhesives, moisture barriers, leveling compounds, or crack isolation membranes if required. Factor in waste percentage based on material (typically 5–15% depending on pattern and room layout). Note transition strips and thresholds between dissimilar floor materials. Identify installation requirements like movement joints, floor prep, and substrate flatness tolerance. Cross-check elevation changes at floor transitions and coordination with finish floor heights.",

  Glazing:
    "Perform a glazing and fenestration takeoff using window schedules, door/window legends, elevations, reflected ceiling plans (for clerestories/skylights), and building sections. Identify and count all window units by type and tag, noting size, frame material (aluminum, vinyl, fiberglass), glass composition (insulated, tempered, laminated, low-E), operability (fixed, casement, sliding), and energy rating. Calculate the total glazing surface area per unit and overall building. Include storefront, curtain wall systems, sidelights, transoms, and interior glass partitions. Account for frames, mullions, fasteners, anchors, and waterproofing sealants. Verify egress compliance for bedrooms, fall protection requirements (guard height, glazing within 18” of the floor), and SHGC/U-value criteria based on climate zone. Include sealant and backer rod quantities for perimeter joint caulking. Review head/jamb/sill details and embedment requirements for aluminum systems. Check fire rating and impact resistance where required by code (e.g., coastal zones, high-rise).",

  HVAC:
    "Generate a comprehensive HVAC takeoff using mechanical drawings, HVAC schedules, control diagrams, and specifications. Identify all mechanical equipment including air handling units (AHUs), roof top units (RTUs), split systems, VAV boxes, exhaust fans, boilers, chillers, cooling towers, thermostats, and dampers. Quantify air terminals (supply diffusers, return grilles, exhaust registers) per room. Measure ductwork lengths, widths, and heights by system (supply, return, exhaust) and include fittings such as elbows, reducers, branches, and transitions. Note duct gauge, insulation type/thickness, and fire/smoke dampers. Include refrigerant piping, hydronic piping, and drain lines as shown on piping schematics. Verify zoning by area and equipment. Check ceiling and wall conflicts with MEP coordination zones. Ensure ventilation rates and equipment capacities match design loads. Document controls (sensors, actuators, control panels) and confirm with sequence of operations. Cross-reference mechanical rooms with architectural and structural for access and clearance.",

  Drywall:
    "Complete an in-depth drywall takeoff using architectural floor plans, reflected ceiling plans, partition schedules, and wall sections. Identify all gypsum board types (standard, moisture-resistant, mold-resistant, abuse-resistant, fire-rated) and thicknesses for each wall type. Calculate square footage of gypsum board on both sides of partitions and on ceilings. Account for soffits, dropped ceilings, shafts, and furr-outs. Include specialty systems such as shaft wall assemblies, sound-rated partitions, and rated corridor walls. Quantify joint treatment levels (Level 1–5) based on finish schedule or specifications. Include metal stud backing, control joints, corner beads, access panels, and acoustical sealant. Deduct areas for large openings (windows, doors) unless stated otherwise. Cross-check partition types against keynotes and legend. Include fasteners, trim accessories, and reveal beads. Confirm assembly details for UL-rated walls or fire-resistance requirements per IBC/UL.",

  Masonry:
    "Execute a full masonry takeoff from elevations, wall sections, structural plans, and detail sheets. Identify all masonry types: CMU, face brick, stone veneer, structural brick, and decorative block. Determine bond patterns (running bond, stack bond, Flemish), mortar type, and reinforcement. Calculate square footage for each wall segment and estimate block/brick count based on unit dimensions. Include vertical and horizontal reinforcement (grout cells, rebar, bond beams), control joints, wall ties, lintels, flashing, and weep holes. Verify bearing walls vs veneer applications. Include insulation (cavity, rigid board), air barriers, and vapor control layers if specified. Include grouting requirements by lift height. Identify support angles, shelf angles, or relieving angles for multi-story construction. Confirm expansion joint spacing and movement joint details. Review thermal and moisture protection layers in masonry cavity walls.",

  "Doors and Windows":
    "Perform a highly detailed takeoff of all door and window assemblies using door/window schedules, hardware sets, elevations, and plan details. Identify door types (wood, hollow metal, aluminum, FRP, glass), frame types (knockdown, welded, thermally broken), leaf sizes, thicknesses, fire ratings, and vision lites. Count all openings and note swing direction, handing, and egress path compliance. Include sidelight and transom assemblies. Extract hardware set numbers and components from the hardware schedule (hinges, closers, locks, panic devices, etc.). Include thresholds, weatherstripping, seals, silencers, and kick plates. For windows, identify operable vs fixed, energy performance (U-factor, SHGC), tinting, safety glazing, and fall protection compliance. Confirm ADA and accessibility compliance for all doors including push/pull clearances and lever hardware. Cross-check wall types for frame anchorage requirements. Include coordination with security, access control, and fire alarm tie-ins.",
};

